# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f frontend/Dockerfile.prod -t "$CI_REGISTRY_IMAGE" frontend
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -f frontend/Dockerfile.prod  -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" frontend
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
#include:
#  - template: Security/SAST.gitlab-ci.yml
