docker-build-master:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile.prod -t "$CI_REGISTRY_IMAGE" frontend
    - docker push "$CI_REGISTRY_IMAGE"

  only:
    - master

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -f Dockerfile.prod  -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" frontend
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
